name: Self-Healing Repository Maintenance

on:
  schedule:
    # Run daily at 3 AM UTC (adjust based on your timezone)
    - cron: '0 3 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  repo-maintenance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for better analysis
      
      - name: Run Claude Code Repo-Updater Agent
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "15" # Keep it short to save API credits
          direct_prompt: |
            Use the repo-updater agent to perform repository maintenance on claude-code-subagents.
            
            Tasks to perform (in order of priority):
            1. Validate all agent configurations in .claude/agents/
            2. Sync any out-of-sync agents between markdown and JSON
            3. Check for and fix any schema violations
            4. ONLY if you find significant improvements: suggest agent optimizations
            
            Be efficient and focused:
            - Skip analysis if everything is already in sync
            - Only suggest changes that provide real value
            - Do not make cosmetic changes
            - Exit early if no issues are found
            
            If changes are needed:
            - Make the minimal necessary fixes
            - Create clear commit messages
            - Summarize what was changed and why
            
            Remember: This runs daily, so only fix actual issues, not hypothetical ones.
          allowed_tools: ["Task", "Read", "Write", "MultiEdit", "Glob", "Grep", "LS", "Bash"]
          
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            fix: automated repository maintenance
            
            🤖 Generated with Claude Code
            
            Co-Authored-By: Claude <noreply@anthropic.com>
          branch: automated/repo-maintenance-${{ github.run_number }}
          delete-branch: true
          title: "🔧 Automated Repository Maintenance"
          body: |
            ## 🤖 Automated Repository Maintenance
            
            This PR was automatically generated by the self-healing repo-updater agent.
            
            ### What Changed
            The repo-updater agent found and fixed issues with agent configurations:
            - Validated all agent definitions
            - Synchronized markdown and JSON files
            - Fixed any schema violations
            - Applied performance optimizations where needed
            
            ### Review Checklist
            - [ ] Agent configurations are valid
            - [ ] No breaking changes introduced
            - [ ] Changes improve repository quality
            
            ---
            *Generated by claude-code-subagents self-healing system*
          labels: |
            automated
            maintenance
            
  # Optional: Auto-merge if tests pass
  auto-merge:
    needs: repo-maintenance
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Auto-merge maintenance PRs
        uses: pascalgn/merge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automated,maintenance"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_REQUIRED_APPROVALS: "0" # Since it's automated
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"