name: Agent Request

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  generate:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[Agent Request]')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Extract agent name from issue
          AGENT_NAME=$(echo "${{ github.event.issue.title }}" | sed 's/.*Request]//' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')
          
          # Generate agent with Claude
          curl -X POST https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d "{
              \"model\": \"claude-3-5-sonnet-20241022\",
              \"max_tokens\": 4096,
              \"messages\": [{
                \"role\": \"user\",
                \"content\": \"Create a simple agent markdown file for: ${{ github.event.issue.body }}\n\nOutput only the markdown content.\"
              }]
            }" | jq -r '.content[0].text' > ".claude/agents/${AGENT_NAME}.md"
          
          # Create branch and commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "agent/${AGENT_NAME}"
          git add .claude/agents/
          git commit -m "feat: add ${AGENT_NAME} agent"
          git push origin "agent/${AGENT_NAME}"
      
      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Agent created! [Create PR](https://github.com/${{ github.repository }}/compare/main...agent/${{ env.AGENT_NAME }})`
            });