name: self-heal

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Maintenance mode'
        required: true
        default: 'light'
        type: choice
        options:
          - light
          - standard
          - deep

permissions:
  contents: write
  actions: read

jobs:
  repo-maintenance:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Claude API for Repo Maintenance
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Simple direct maintenance
          MODE="${{ github.event.inputs.mode || 'light' }}"
          
          # Call Claude API with Sonnet for better analysis
          curl -X POST https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -d "{
              \"model\": \"claude-3-5-sonnet-20241022\",
              \"max_tokens\": 4096,
              \"messages\": [{
                \"role\": \"user\",
                \"content\": \"As a senior code reviewer, analyze the claude-code-subagents repository structure in .claude/. Check for: 1) Valid agents.json syntax, 2) Sync between markdown files and JSON entries, 3) Agent configuration completeness. Format your response as a professional code review with sections for Summary, Positive Changes, Concerns (if any), and Recommendations. Use markdown formatting with emojis where appropriate (✅ for positive, ⚠️ for warnings, 🔍 for observations).\"
              }]
            }" > response.json
          
          # Check response
          if grep -q "VALID" response.json; then
            echo "✅ Repository is healthy"
          else
            echo "⚠️ Repository needs maintenance"
            # For now, just log - in full version would run repo-updater
          fi
      
      - name: Commit any fixes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # If there are changes, commit them
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "chore: automated maintenance [skip ci]"
            git push
          fi