name: Self-Healing Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Maintenance mode'
        required: true
        default: 'light'
        type: choice
        options:
          - light
          - standard
          - deep

jobs:
  repo-maintenance:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'automated repository maintenance')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Repo Updater via Claude API
        id: claude
        run: |
          response=$(curl -X POST https://api.anthropic.com/v1/messages \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -d '{
              "model": "claude-3-opus-20240229",
              "max_tokens": 4096,
              "messages": [{
                "role": "user",
                "content": "@agent-repo-updater\nMode: ${{ github.event.inputs.mode || 'light' }}\nTask: Check and fix .claude/agents/ configurations. Only output the commands to run, no explanations."
              }]
            }' | jq -r '.content[0].text')
          
          echo "$response" > commands.sh
          bash commands.sh || true
      
      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create PR
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fix: automated repository maintenance"
          branch: auto/maintenance-${{ github.run_number }}
          title: "🔧 Automated Repository Maintenance"