name: Self-Healing Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: 'Maintenance mode'
        required: true
        default: 'light'
        type: choice
        options:
          - light
          - standard
          - deep

jobs:
  repo-maintenance:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'automated repository maintenance')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Claude Code
        uses: anthropics/claude-code@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          command: |
            @agent-repo-updater
            Mode: ${{ github.event.inputs.mode || 'light' }}
            Task: Validate and fix agent configurations in .claude/
      
      - name: Create PR if changes
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fix: automated repository maintenance"
          branch: auto/maintenance-${{ github.run_number }}
          title: "🔧 Automated Repository Maintenance"
          body: "The repo-updater agent found and fixed issues."